## Streszczenie {-}

<!-- (1) 1-3 zdania wstępu do problemu (czym się zajmujemy, dlaczego jest to ważne, jakie są problemy/luki do wypełnienia) -->
Ocena dynamiki zmian pokrycia terenu ma ważne znaczenie dla skutecznego planowania i zarządzania zasobami.
<!-- W wyniku programów monitorowania zmian pokrycia terenu powstają liczne zbiory danych umożliwiające wykonanie takich analiz nawet w skali globalnej. -->
<!-- Większość analiz zmian pokrycia terenu wykonanych w przeszłości, skupiała się wyłącznie na aspektach ilości i lokalizacji zachodzących zmian. -->
<!-- (2) 1 zdanie opisujące cel pracy -->
Celem tej pracy było określenie <!--zmian ilościowych oraz charakteru przestrzennego głównych -->zmian pokrycia terenu na obszarze Polski w latach 1990-2018 dodatkowo rozszerzając istniejące metody analiz przestrzennych o analizy struktur przestrzennych.
<!-- (3) 1-3 zdania przedstawiające użyte materiały (dane) i metody (techniki, narzędzia), -->
Do pracy wykorzystane zostały zbiory danych przestrzennych o pokryciu terenu CORINE Land Cover (CLC).
Zmiany ilościowe zostały obliczone z użyciem algebry rastrów.
Analiza przestrzennego charakteru zmian pokrycia terenu wykonana została w oparciu o metody wykorzystujące obliczenia sygnatur przestrzennych dla mniejszych obszarów wydzielonych z obszaru badań.
<!-- (4) 1-3 zdania obrazujące główne wyniki pracy -->
Wynikiem pracy są informacje o najważniejszych kierunkach zmian pokrycia terenu na obszarze Polski w latach 1990-2018.

<!-- Słowa kluczowe: (4-6 słów/zwrotów opisujących treść pracy, które nie wystąpiły w tytule) -->
Słowa kluczowe: struktura przestrzenna, sygnatury przestrzenne, pokrycie terenu, CORINE Land Cover, CLC

## Abstract {-}

Assessing land cover change dynamics is important for effective planning and resource management.
The aim of this study was to determine the changes in land cover in Poland in the years 1990-2018, additionally extending the existing methods of spatial analyzes with analyzes of spatial patterns.
The analysis is based on CORINE Land Cover (CLC) spatial data sets.
Quantitative changes were calculated using raster algebra.
The spatial analysis of land cover changes was performed using methods that utilize calculation of spatial signatures for regions made by dividing the study area into smaller fragments.
The result of the work is information on the most important directions of land cover changes in Poland in 1990-2018.

Keywords: spatial patterns, spatial signatures, land cover, CORINE Land Cover, CLC

\newpage

\setstretch{1.2}\sf\tighttoc\doublespacing
