# Wprowadzenie {#wprowadzenie}

<!-- 1.Co to jest pokrycie terenu? -->
Pokrycie terenu stanowi wszelkie obiekty znajdujące się na powierzchni Ziemi związane zarówno ze skutkami sił przyrody, jak i działalności człowieka. Wśród tych obiektów znajduje się rzeźba terenu, zjawiska hydrograficzne, kompleksy roślinne oraz wszelkie formy antropogeniczne [@Oledzki1987].
Pokrycie terenu dla dużych obszarów zazwyczaj opisywane jest za pomocą danych o pokryciu terenu.

<!-- 2.Co to monitorowanie tego pokrycia i po co? -->

W ostatnich latach, zmiany wywołane przez człowieka znacząco wpłynęły na otaczające nas środowisko [@Radwan_2021; @NOWOSAD2019332; @Mucher_EU].
Zmiany pokrycia terenu mają bezpośredni wpływ na zmiany klimatu i warunki środowiskowe.
Antropogeniczne zmiany pokrycia terenu stanowią szczególne zagrożenie dla prawidłowego funkcjonowania ekosystemów [@Verburg_2011].
Znaczna ich część może mieć negatywny wpływ zarówno na środowisko [@Tai_2014], jak i działalność człowieka [@Feddema_2006].
Dlatego też monitorowanie zmian pokrycia terenu, a także ocena dynamiki tych zmian ma pierwszorzędne znaczenie dla skutecznego planowania i zarządzania zasobami.

Jednym z programów, których celem jest monitorowanie pokrycia terenu, jest program CORINE przyjęty w 1985 roku przez Komisję Wspólnot Europejskich.
Program ten oparty jest o analizy licznych obrazów satelitarnych, które następnie są interpretowane do uproszczonej postaci danych podzielonych na ustalone kategorie pokrycia terenu.
Do wyników programu CORINE należą, między innymi, zbiory danych o pokryciu terenu CORINE Land Cover (CLC), obejmujące obszarem większość państw europejskich.
Dane te są szczególnie popularne w celach analiz zmian pokrycia terenu [@Mierzwiak_Całka_2019; @Ciolkosz_Polawski_2006].

<!-- Metody analiz pokrycia terenu -->
Zmiany pokrycia terenu można analizować przy użyciu różnych metod.
Najbardziej podstawowym sposobem jest prosta analiza zmian ilościowych pokrycia terenu na analizowanym obszarze.
Inny sposób, oparty o metody wywodzące się z dziedziny ekologii krajobrazów, polega na podzieleniu obszaru badań na mniejsze jednostki przestrzenne, a następnie wykonanie różnorodnych analiz wewnątrz tych jednostek [@NOWOSAD2019332].
Analizy można wykonać dla obszarów regularnych lub nieregularnych.
Podstawowa metoda podziału na obszary regularne zakłada podzielenie dużego regionu na mniejsze obszary o kształcie kwadratu.
Innym podejściem jest podział na obszary nieregularne, które mogą być wynikiem wcześniejszych badań (np. ekoregiony) lub reprezentować pewne istniejące granice, takie jak podziały administracyjne [@nowosad_motif].

<!-- Coś o sygnaturach przestrzennych -->
Jednym z rodzajów wspomnianych powyżej analiz są analizy oparte o sygnatury przestrzenne.
Sygnatury przestrzenne stanowią statystyczny opis pewnych struktur przestrzennych występujących wewnątrz rastra [@nowosad_motif; @Jasiewicz_GeoPAT].
Takie podejście do analizy przestrzennej umożliwia między innymi ocenę zmian przestrzennej kompozycji i konfiguracji analizowanych jednostek przestrzennych.

<!-- 5.Cel -->
Głównym celem tej pracy jest analiza ogólnego charakteru oraz przestrzennego rozmieszczenia głównych zmian pokrycia terenu na obszarze Polski w latach 1990-2018.
Poza ogólnymi zmianami ilościowymi obliczonymi dla całego analizowanego obszaru, w pracy uwzględniono także analizy struktur przestrzennych na podstawie obliczeń sygnatur przestrzennych dla mniejszych obszarów wydzielonych z obszaru badań.
Dodatkowym celem było znalezienie i graficzna reprezentacja najbardziej zmienionych obszarów w przeciągu ostatnich 28 lat oraz sporządzenie map pokrycia terenu Polski, opartych o dane CORINE Land Cover dla lat 1990 i 2018 zreklasyfikowane do 7 kategorii pokrycia terenu, umożliwiających ogólną ocenę stanu pokrycia terenu dla tych lat.
