# Przegląd literatury {#lit}

<!-- Global assessment and mapping of changes in mesoscale landscapes: 1992–2015 Jakub Nowosad, Tomasz F. Stepinski,Pawel Netzel -->
W pracy [@NOWOSAD2019332] przedstawione zostały metody analizy globalnych zmian pokrycia terenu z wykorzystaniem technik opartych o analizy struktur przestrzennych, na których bazuje ta praca.
Jednakże, ze względu na zastosowanie w powyższej pracy danych o pokryciu terenu pochodzących z programu ESA Climate Change Initiative (ESA CCI) o rozdzielczości przestrzennej 300m, wynikowa mapa globalnych zmian pokrycia terenu w latach 1992-2015 umożliwia określenie trendów zmian przestrzennych w badanym okresie wyłącznie w skali globalnej.
W tej pracy, w celu wykonania szczegółowej analizy, bardziej dostosowanej do rozmiaru państw europejskich, wykorzystano dane o pokryciu terenu udostępniane w ramach europejskiego programu CORINE.
Dane wynikowe programu CORINE użyte do celów tej pracy zostały bardziej wnikliwie opisane w podrozdziale \@ref(clc).

<!-- Land cover characterization and change detection for environmental monitoring of pan-Europe -->
Analiza w skali europejskiej przedstawiona została w pracy [@Mucher_EU].
W pracy tej opracowana została metoda umożliwiająca uzyskanie ogólnoeuropejskiej bazy danych pokrycia terenu o rozdzielczości przestrzennej 1 km, którą można w łatwy sposób aktualizować za pomocą danych satelitarnych.
Jednakże, sam autor zwrócił uwagę na ograniczenia w monitorowaniu zmian przestrzennych wynikające z niewielkiej rozdzielczości przestrzennej użytych danych, co było powodem wykorzystania dodatkowych technik wykrywania zmian.

<!-- Zmiany pokrycia terenu w Polsce w latach 1990-2012 na podstawie danych CORINE Land Cover, Mierzwiak-->
Dla obszaru Polski, analiza zmian pokrycia terenu została wykonana w publikacji autorstwa [@Mierzwiak_Całka_2019].
Analiza ta została przeprowadzona dla lat 1990-2012 i także została oparta na danych pochodzących z programu CORINE.
W przeciwieństwie do wspomnianej pracy, w tej pracy nie zostały wykorzystane bazy danych zmian pokrycia terenu między produktami programu CORINE.
Zamiast tego, użyto produkty tego programu w postaci rastrowych map pokrycia terenu CORINE Land Cover dla lat 1990 i 2018.
Statystyki dotyczące zmian pokrycia terenu między analizowanymi rastrami zostały obliczone za pomocą podstawowej algebry rastrów.
Co więcej, podejście do analizy zmian przestrzennych zostało rozszerzone o analizę struktur przestrzennych na podstawie metod przedstawionych w pracy [@NOWOSAD2019332].
