# Metody {#metody}

## Reklasyfikacja danych CLC
W celu zwiększenia przejrzystości analizy, klasy występujące na analizowanym obszarsze zostały poddane reklasyfikacji.
Dla trzeciego poziomu szczegółowości danych rastrowych CORINE Land Cover wyróżnione zostały 44 klasy pokrycia terenu.
Na terytorium Polski spośród 44 możliwych klas występują 33 klasy.

W wyniku reklasyfikacji, ostateczna ilość klas została zmniejszona do 7.
Wyróżnione klasy to: tereny antropogeniczne, tereny rolne, lasy, tereny krzewiaste, tereny z rzadszą roślinnością, obszary podmokłe, obszary wodne.
Ostatecznie, wartości pikseli z danych rastrowych CLC zostały zamienione na nowe

**Mapy pokazujące jak wygląda fragment terenu przed i po reklasyfikacji**
**Tabelka/wykres pokazujące co zostało zreklasyfikowane w co innego?**

## Wykorzystane oprogramowanie
Wszystkie obliczenia i ryciny zostały przygotowane za pomocą języka R.
Najważniejszym pakietem języka R, który umożliwił przeprowadzenie analiz zmian strukury przestrzennej był pakiet *motif* [@R-motif].
Wizualizacje danych przestrzennych stworzone zostały z wykorzystaniem pakietu *tmap* [@R-tmap], natomiast do wizualizacji danych ilościowych wykorzystany został pakiet *ggplot2* [@R-ggplot2].

<!--
Wykorzystane pakiety:
motif - analiza przestrzenna wzorców
sf, stars, raster - obróbka danych przestrzennych
tmap, ggplot2, treemapify - wizualizacja danych
dplyr, tidyr, stringr, readr, purrr
-->

## Analiza struktury przestrzennej
W celu trafnego stwierdzenia prawidłowości dotyczących zmian struktury przestrzennej, dane zostały przeanalizowane na czterech poziomach: dla całego zbioru danych (t.j. na poziomie krajowym), poprzez wydobycie wartości dla kwadratów o wymiarach 100x100 pikseli, na poziomie powiatowym oraz na poziomie mezoregionów.
Kwadraty stanowiące siatkę regularnych krajobrazów lokalnych obejmują powierzchnię 100 kilometrów kwadratowych.

<!--
Rozdział **Metody** zawiera opis użytych metod (np. statystycznych czy geostatystycznych) oraz technologii (np. pakiety R).
Opis każdej z metod czy technologi powinien być zwarty i zawierać tylko najważniejsze informacje z punktu widzenia pracy dyplomowej.

Każda użyta metoda i technologia powinna być zacytowana.
W przypadku pakietów R, wystarczy wypełnić poniższy blok kodu (zwróć uwagę, że ten blok kodu ma parametr `echo=FALSE`; oznacza to, że będzie on niewidoczny w wynikowym pliku PDF)...
--->

```{r pakiertbib, echo=FALSE, warning=FALSE}
pakiety = c("base", "motif", "raster", "stars", "sf", "tmap", "ggplot2", "treemapify",
            "dplyr", "tidyr", "stringr", "readr", "purrr")

knitr::write_bib(pakiety, "packages.bib", width = 60)
```

<!--
... a następnie zacytować pakiet używając znaku `@`, po którym podać nazwę pakietu rozpoczynającą się od prefiksu `R-`.
Przykładowe cytowanie języka R bez nawiasu to @R-base, a pakietu **kableExtra** w nawiasie to [@R-kableExtra].
Więcej przykładów cytowania można znaleźć na stronie https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citations.

W przypadkach, gdy cytowanie istnieje, ale nie jest pakietem R to należy dodać je do pliku `thesis.bib` i użyć powyższej składni ze znakiem `@`.
W ostateczności, gdy dana technologia nie posiada cytowania, należy podać jej adres internetowy.
-->
